name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org/"

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
          run_install: |
            - recursive: false

      - name: build
        run: pnpm run build

      - name: publish npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
